version: "1.0.{build}"
os: Visual Studio 2019

environment:
  global:
    BOOST_INCLUDEDIR: "C:/Libraries/boost_1_71_0"
    BOOST_LIBRARYDIR: "C:/Libraries/boost_1_71_0/lib64-msvc-14.2"

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 ..

build_script:
  - cmd: cmake --build . --config Release -- /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - cmd: bin\\Release\\invio-test -r junit -o results.xml

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = 'results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))